package main

import "log"
import "errors"

func main(){
    try{
        //@errcheck
        a, err:=functionWithError() 
        log.Println("computed a...")

        //@errcheck
        b, err:=functionWithError()
        log.Println("computed b...")

        //@errcheck
        c, err:=functionWithError()
        log.Println("computed c...")

        log.Println(a,b,c)
    } catch {
        log.Println(err)
    }
}

func functionWithError() (string, error){
    return "", errors.New("У вас ошибка!")
}